title: Blog de Analítica Avanzada
description: Análisis de Datos con Spark y Big Data
author: Alejandro De Mendoza Tovar
baseurl: ""
url: ""

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed