title: Blog de Analítica Avanzada
description: Análisis de Datos con Spark y Big Data
author: Maria Fernanda
baseurl: ""
url: ""
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap